using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using VNVTStore.Application.Interfaces;
using VNVTStore.Domain.Entities;
using VNVTStore.Domain.Enums;

namespace VNVTStore.Application.Seeding;

public static class DataSeeder
{
    public static async Task SeedAsync(IApplicationDbContext context, IPasswordHasher passwordHasher)
    {
        // 1. Seed Admin User
        var adminExists = await context.TblUsers.AnyAsync(u => u.Username == "admin");
        if (!adminExists)
        {
            var admin = TblUser.Create(
                "admin",
                "admin@vnvtstore.com",
                passwordHasher.Hash("Admin@123"),
                "System Administrator",
                UserRole.Admin
            );
            context.TblUsers.Add(admin);
            Console.WriteLine("Seeded Admin User: admin / Admin@123");
        }

        // 2. Seed Base Data (Category, Brand, Unit)
        var category = await context.TblCategories.FirstOrDefaultAsync();
        if (category == null)
        {
            category = new TblCategory { Code = "CAT001", Name = "General", IsActive = true };
            context.TblCategories.Add(category);
        }

        var brand = await context.TblBrands.FirstOrDefaultAsync();
        if (brand == null)
        {
            brand = new TblBrand { Code = "BRAND001", Name = "Generic Brand", IsActive = true };
            context.TblBrands.Add(brand);
        }

        var unit = await context.TblUnits.FirstOrDefaultAsync();
        if (unit == null)
        {
            unit = new TblUnit { Code = "PCS", Name = "Cái" };
            context.TblUnits.Add(unit);
        }

        await context.SaveChangesAsync(default);

        // 3. Seed 100 Products
        var productCount = await context.TblProducts.CountAsync();
        if (productCount < 100)
        {
            int productsToCreate = 100 - productCount;
            var random = new Random();

            for (int i = 1; i <= productsToCreate; i++)
            {
                var productCode = $"PRD{productCount + i:D3}";
                var product = TblProduct.Create(
                    name: $"Sản phẩm mẫu {productCount + i}",
                    price: random.Next(100000, 5000000),
                    wholesalePrice: random.Next(80000, 4000000),
                    stock: random.Next(10, 500),
                    categoryCode: category.Code,
                    costPrice: random.Next(50000, 3000000),
                    supplierCode: null,
                    brandCode: brand.Code,
                    baseUnit: unit.Code
                );

                // Use the code generated by factory or set it if needed
                // factory method sets Guid, but if we want sequential:
                // product.Code = productCode; // Set sequential code for easier tracking

                context.TblProducts.Add(product);

                // Add Unit
                context.TblProductUnits.Add(new TblProductUnit
                {
                    Code = Guid.NewGuid().ToString("N").Substring(0, 10),
                    ProductCode = product.Code,
                    UnitCode = unit.Code,
                    ConversionRate = 1,
                    Price = product.Price,
                    IsBaseUnit = true
                });

                // Add Details
                context.TblProductDetails.Add(new TblProductDetail
                {
                    Code = Guid.NewGuid().ToString("N").Substring(0, 10),
                    ProductCode = product.Code,
                    DetailType = ProductDetailType.SPEC,
                    SpecName = "Chất liệu",
                    SpecValue = "Cao cấp"
                });

                context.TblProductDetails.Add(new TblProductDetail
                {
                    Code = Guid.NewGuid().ToString("N").Substring(0, 10),
                    ProductCode = product.Code,
                    DetailType = ProductDetailType.SPEC,
                    SpecName = "Xuất xứ",
                    SpecValue = "Việt Nam"
                });

                // Add Image (File record)
                var imageFile = TblFile.Create(
                    fileName: $"{product.Code}_main.jpg",
                    originalName: "product.jpg",
                    extension: ".jpg",
                    mimeType: "image/jpeg",
                    size: 50000,
                    path: $"https://picsum.photos/seed/{product.Code}/600/600",
                    masterCode: product.Code,
                    masterType: "Product"
                );
                context.TblFiles.Add(imageFile);
            }

            await context.SaveChangesAsync(default);
            Console.WriteLine($"Successfully seeded {productsToCreate} products.");
        }
    }
}
