
using Moq;
using VNVTStore.Application.Carts.Commands;
using VNVTStore.Application.Carts.Queries;
using VNVTStore.Domain.Entities;
using VNVTStore.Domain.Interfaces;
using VNVTStore.Application.Interfaces;
using System.Linq.Expressions;
using VNVTStore.Application.Carts.Handlers;
using AutoMapper;
using VNVTStore.Application.DTOs;

namespace VNVTStore.Tests.Carts;

public class CartTests
{
    private readonly Mock<ICartService> _cartServiceMock;
    private readonly Mock<IRepository<TblProduct>> _productRepositoryMock;
    private readonly Mock<IUnitOfWork> _unitOfWorkMock;
    private readonly Mock<IMapper> _mapperMock;

    public CartTests()
    {
        _cartServiceMock = new Mock<ICartService>();
        _productRepositoryMock = new Mock<IRepository<TblProduct>>();
        _unitOfWorkMock = new Mock<IUnitOfWork>();
        _mapperMock = new Mock<IMapper>();
    }

    [Fact]
    public async Task AddToCart_ValidItem_AddsToCart()
    {
        // Arrange
        var userId = Guid.NewGuid();
        var userCode = "USR001";
        var productCode = "P001";
        var command = new AddToCartCommand(userCode, productCode, 1, null, null);
        
        var cart = TblCart.Create(userCode);
        var product = TblProduct.Create("Test Product", 100, 10, null, "SKU123");
        // We cannot force Code property to "P001" via Create or setter (private).
        // Since we mock repository, we can just return this product when asked for "P001".
        // HOWEVER, the logic might check `product.Code`.
        // If `product.Code` is generated by Create, it won't be "P001".
        // Reflection could set it, or we rely on the fact that Handler gets this object from Repo.
        // But if Handler compares product.Code with command.ProductCode?
        // AddToCartHandler: `cart.AddItem(request.ProductCode, ...)`
        // `product` is used to check stock. `product.StockQuantity`.
        // It seems `product.Code` is not strictly compared inside AddItem logic against request?
        // Actually, TblCart.AddItem takes productCode.
        // Ideally, we should set Code using reflection or Mock?
        // Or just let it be random and ensure Repo returns it.
        // But AddItem stores productCode.
        
        // Let's use reflection to set Code if needed, or just assume it works if we don't assert specific Code dependency inside Handler logic (other than matching what was passed).
        // Actually, let's use reflection to set the code to ensure consistency.
        typeof(TblProduct).GetProperty("Code")!.SetValue(product, productCode);

        _cartServiceMock.Setup(x => x.GetOrCreateCartAsync(userCode, It.IsAny<CancellationToken>()))
            .ReturnsAsync(cart);

        _productRepositoryMock.Setup(x => x.GetByCodeAsync(productCode, It.IsAny<CancellationToken>()))
            .ReturnsAsync(product);
            
        _mapperMock.Setup(x => x.Map<CartDto>(cart)).Returns(new CartDto());

        var handler = new CartHandlers(
            _cartServiceMock.Object,
            _productRepositoryMock.Object,
            _unitOfWorkMock.Object,
            _mapperMock.Object);

        // Act
        var result = await handler.Handle(command, CancellationToken.None);

        // Assert
        Assert.True(result.IsSuccess);
        _unitOfWorkMock.Verify(x => x.CommitAsync(It.IsAny<CancellationToken>()), Times.Once);
    }

    [Fact]
    public async Task GetCart_ExistingCart_ReturnsCart()
    {
        // Arrange
        var userCode = "USR001";
        var query = new GetCartQuery(userCode);
        var cart = TblCart.Create(userCode);

        _cartServiceMock.Setup(x => x.GetOrCreateCartAsync(userCode, It.IsAny<CancellationToken>()))
            .ReturnsAsync(cart);
            
        _mapperMock.Setup(x => x.Map<CartDto>(cart)).Returns(new CartDto());

        var handler = new CartHandlers(
             _cartServiceMock.Object,
             _productRepositoryMock.Object,
             _unitOfWorkMock.Object,
             _mapperMock.Object);

        // Act
        var result = await handler.Handle(query, CancellationToken.None);

        // Assert
        Assert.True(result.IsSuccess);
    }
}
