// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VNVTStore.Infrastructure.Persistence;

#nullable disable

namespace VNVTStore.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260108165353_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("address_code_seq");

            modelBuilder.HasSequence("cart_code_seq");

            modelBuilder.HasSequence("cartitem_code_seq");

            modelBuilder.HasSequence("category_code_seq");

            modelBuilder.HasSequence("coupon_code_seq");

            modelBuilder.HasSequence("order_code_seq");

            modelBuilder.HasSequence("orderitem_code_seq");

            modelBuilder.HasSequence("payment_code_seq");

            modelBuilder.HasSequence("product_code_seq");

            modelBuilder.HasSequence("productimage_code_seq");

            modelBuilder.HasSequence("productpromotion_code_seq");

            modelBuilder.HasSequence("promotion_code_seq");

            modelBuilder.HasSequence("quote_code_seq");

            modelBuilder.HasSequence("review_code_seq");

            modelBuilder.HasSequence("user_code_seq");

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblAddress", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValueSql("('ADR'::text || lpad((nextval('address_code_seq'::regclass))::text, 6, '0'::text))");

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Country")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValueSql("'Vietnam'::character varying");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool?>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("PostalCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Code")
                        .HasName("TblAddress_pkey");

                    b.HasIndex("UserCode");

                    b.ToTable("TblAddress", (string)null);
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblCart", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValueSql("('CRT'::text || lpad((nextval('cart_code_seq'::regclass))::text, 6, '0'::text))");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Code")
                        .HasName("TblCart_pkey");

                    b.HasIndex(new[] { "UserCode" }, "idx_cart_user");

                    b.ToTable("TblCart", (string)null);
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblCartItem", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValueSql("('CRI'::text || lpad((nextval('cartitem_code_seq'::regclass))::text, 6, '0'::text))");

                    b.Property<DateTime?>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CartCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Code")
                        .HasName("TblCartItem_pkey");

                    b.HasIndex("CartCode");

                    b.HasIndex("ProductCode");

                    b.ToTable("TblCartItem", (string)null);
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblCategory", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValueSql("('CAT'::text || lpad((nextval('category_code_seq'::regclass))::text, 6, '0'::text))");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("ImageURL");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ParentCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Code")
                        .HasName("TblCategory_pkey");

                    b.HasIndex("ParentCode");

                    b.ToTable("TblCategory", (string)null);
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblCoupon", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValueSql("('CPN'::text || lpad((nextval('coupon_code_seq'::regclass))::text, 6, '0'::text))");

                    b.Property<string>("PromotionCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int?>("UsageCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Code")
                        .HasName("TblCoupon_pkey");

                    b.HasIndex("PromotionCode");

                    b.ToTable("TblCoupon", (string)null);
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblOrder", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValueSql("('ORD'::text || lpad((nextval('order_code_seq'::regclass))::text, 6, '0'::text))");

                    b.Property<string>("AddressCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("CouponCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal?>("DiscountAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("FinalAmount")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<DateTime?>("OrderDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValueSql("'pending'::character varying");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Code")
                        .HasName("TblOrder_pkey");

                    b.HasIndex("AddressCode");

                    b.HasIndex("CouponCode");

                    b.HasIndex("UserCode");

                    b.HasIndex(new[] { "Status" }, "idx_order_status");

                    b.ToTable("TblOrder", (string)null);
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblOrderItem", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValueSql("('ORI'::text || lpad((nextval('orderitem_code_seq'::regclass))::text, 6, '0'::text))");

                    b.Property<decimal?>("DiscountAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasDefaultValueSql("0");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal>("PriceAtOrder")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<string>("ProductCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Code")
                        .HasName("TblOrderItem_pkey");

                    b.HasIndex("OrderCode");

                    b.HasIndex("ProductCode");

                    b.ToTable("TblOrderItem", (string)null);
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblPayment", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValueSql("('PAY'::text || lpad((nextval('payment_code_seq'::regclass))::text, 6, '0'::text))");

                    b.Property<decimal>("Amount")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("PaymentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValueSql("'pending'::character varying");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("TransactionID");

                    b.HasKey("Code")
                        .HasName("TblPayment_pkey");

                    b.HasIndex(new[] { "OrderCode" }, "TblPayment_OrderCode_key")
                        .IsUnique();

                    b.ToTable("TblPayment", (string)null);
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblProduct", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValueSql("('PRD'::text || lpad((nextval('product_code_seq'::regclass))::text, 6, '0'::text))");

                    b.Property<string>("CategoryCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal?>("CostPrice")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<string>("Sku")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("SKU");

                    b.Property<int?>("StockQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("SupplierCode")
                        .HasColumnType("text");

                    b.Property<string>("SupplierCodeNavigationCode")
                        .HasColumnType("character varying");

                    b.Property<decimal?>("Weight")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.HasKey("Code")
                        .HasName("TblProduct_pkey");

                    b.HasIndex("CategoryCode");

                    b.HasIndex("SupplierCodeNavigationCode");

                    b.HasIndex(new[] { "Sku" }, "TblProduct_SKU_key")
                        .IsUnique();

                    b.HasIndex(new[] { "Name" }, "idx_product_name");

                    b.ToTable("TblProduct", (string)null);
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblProductImage", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValueSql("('IMG'::text || lpad((nextval('productimage_code_seq'::regclass))::text, 6, '0'::text))");

                    b.Property<string>("AltText")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("ImageURL");

                    b.Property<bool?>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int?>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Code")
                        .HasName("TblProductImage_pkey");

                    b.HasIndex("ProductCode");

                    b.ToTable("TblProductImage", (string)null);
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblProductPromotion", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValueSql("('PPROM'::text || lpad((nextval('productpromotion_code_seq'::regclass))::text, 6, '0'::text))");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("PromotionCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Code")
                        .HasName("TblProductPromotion_pkey");

                    b.HasIndex("PromotionCode");

                    b.HasIndex(new[] { "ProductCode", "PromotionCode" }, "TblProductPromotion_ProductCode_PromotionCode_key")
                        .IsUnique();

                    b.ToTable("TblProductPromotion", (string)null);
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblPromotion", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValueSql("('PROM'::text || lpad((nextval('promotion_code_seq'::regclass))::text, 6, '0'::text))");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("DiscountValue")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("MaxDiscountAmount")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<decimal?>("MinOrderAmount")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("UsageLimit")
                        .HasColumnType("integer");

                    b.HasKey("Code")
                        .HasName("TblPromotion_pkey");

                    b.ToTable("TblPromotion", (string)null);
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblQuote", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValueSql("('QT'::text || lpad((nextval('quote_code_seq'::regclass))::text, 6, '0'::text))");

                    b.Property<string>("AdminNote")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<decimal?>("QuotedPrice")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValueSql("'pending'::character varying");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Code")
                        .HasName("TblQuote_pkey");

                    b.HasIndex("ProductCode");

                    b.HasIndex("UserCode");

                    b.ToTable("TblQuote", (string)null);
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblReview", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValueSql("('REV'::text || lpad((nextval('review_code_seq'::regclass))::text, 6, '0'::text))");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool?>("IsApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("OrderItemCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Code")
                        .HasName("TblReview_pkey");

                    b.HasIndex("OrderItemCode");

                    b.HasIndex("UserCode");

                    b.ToTable("TblReview", (string)null);
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblSupplier", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("character varying");

                    b.Property<string>("Address")
                        .HasColumnType("character varying");

                    b.Property<string>("BankAccount")
                        .HasColumnType("character varying");

                    b.Property<string>("BankName")
                        .HasColumnType("character varying");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("character varying");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("character varying");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("character varying");

                    b.Property<string>("TaxCode")
                        .HasColumnType("character varying");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Code")
                        .HasName("TblSupplier_pkey");

                    b.ToTable("TblSupplier", (string)null);
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblUser", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValueSql("('USR'::text || lpad((nextval('user_code_seq'::regclass))::text, 6, '0'::text))");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValueSql("'customer'::character varying");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Code")
                        .HasName("TblUser_pkey");

                    b.HasIndex(new[] { "Email" }, "TblUser_Email_key")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "TblUser_Username_key")
                        .IsUnique();

                    b.ToTable("TblUser", (string)null);
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblAddress", b =>
                {
                    b.HasOne("VNVTStore.Domain.Entities.TblUser", "UserCodeNavigation")
                        .WithMany("TblAddresses")
                        .HasForeignKey("UserCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("TblAddress_UserCode_fkey");

                    b.Navigation("UserCodeNavigation");
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblCart", b =>
                {
                    b.HasOne("VNVTStore.Domain.Entities.TblUser", "UserCodeNavigation")
                        .WithMany("TblCarts")
                        .HasForeignKey("UserCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("TblCart_UserCode_fkey");

                    b.Navigation("UserCodeNavigation");
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblCartItem", b =>
                {
                    b.HasOne("VNVTStore.Domain.Entities.TblCart", "CartCodeNavigation")
                        .WithMany("TblCartItems")
                        .HasForeignKey("CartCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("TblCartItem_CartCode_fkey");

                    b.HasOne("VNVTStore.Domain.Entities.TblProduct", "ProductCodeNavigation")
                        .WithMany("TblCartItems")
                        .HasForeignKey("ProductCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("TblCartItem_ProductCode_fkey");

                    b.Navigation("CartCodeNavigation");

                    b.Navigation("ProductCodeNavigation");
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblCategory", b =>
                {
                    b.HasOne("VNVTStore.Domain.Entities.TblCategory", "ParentCodeNavigation")
                        .WithMany("InverseParentCodeNavigation")
                        .HasForeignKey("ParentCode")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("TblCategory_ParentCode_fkey");

                    b.Navigation("ParentCodeNavigation");
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblCoupon", b =>
                {
                    b.HasOne("VNVTStore.Domain.Entities.TblPromotion", "PromotionCodeNavigation")
                        .WithMany("TblCoupons")
                        .HasForeignKey("PromotionCode")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("TblCoupon_PromotionCode_fkey");

                    b.Navigation("PromotionCodeNavigation");
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblOrder", b =>
                {
                    b.HasOne("VNVTStore.Domain.Entities.TblAddress", "AddressCodeNavigation")
                        .WithMany("TblOrders")
                        .HasForeignKey("AddressCode")
                        .HasConstraintName("TblOrder_AddressCode_fkey");

                    b.HasOne("VNVTStore.Domain.Entities.TblCoupon", "CouponCodeNavigation")
                        .WithMany("TblOrders")
                        .HasForeignKey("CouponCode")
                        .HasConstraintName("TblOrder_CouponCode_fkey");

                    b.HasOne("VNVTStore.Domain.Entities.TblUser", "UserCodeNavigation")
                        .WithMany("TblOrders")
                        .HasForeignKey("UserCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("TblOrder_UserCode_fkey");

                    b.Navigation("AddressCodeNavigation");

                    b.Navigation("CouponCodeNavigation");

                    b.Navigation("UserCodeNavigation");
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblOrderItem", b =>
                {
                    b.HasOne("VNVTStore.Domain.Entities.TblOrder", "OrderCodeNavigation")
                        .WithMany("TblOrderItems")
                        .HasForeignKey("OrderCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("TblOrderItem_OrderCode_fkey");

                    b.HasOne("VNVTStore.Domain.Entities.TblProduct", "ProductCodeNavigation")
                        .WithMany("TblOrderItems")
                        .HasForeignKey("ProductCode")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("TblOrderItem_ProductCode_fkey");

                    b.Navigation("OrderCodeNavigation");

                    b.Navigation("ProductCodeNavigation");
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblPayment", b =>
                {
                    b.HasOne("VNVTStore.Domain.Entities.TblOrder", "OrderCodeNavigation")
                        .WithOne("TblPayment")
                        .HasForeignKey("VNVTStore.Domain.Entities.TblPayment", "OrderCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("TblPayment_OrderCode_fkey");

                    b.Navigation("OrderCodeNavigation");
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblProduct", b =>
                {
                    b.HasOne("VNVTStore.Domain.Entities.TblCategory", "CategoryCodeNavigation")
                        .WithMany("TblProducts")
                        .HasForeignKey("CategoryCode")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("TblProduct_CategoryCode_fkey");

                    b.HasOne("VNVTStore.Domain.Entities.TblSupplier", "SupplierCodeNavigation")
                        .WithMany()
                        .HasForeignKey("SupplierCodeNavigationCode");

                    b.Navigation("CategoryCodeNavigation");

                    b.Navigation("SupplierCodeNavigation");
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblProductImage", b =>
                {
                    b.HasOne("VNVTStore.Domain.Entities.TblProduct", "ProductCodeNavigation")
                        .WithMany("TblProductImages")
                        .HasForeignKey("ProductCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("TblProductImage_ProductCode_fkey");

                    b.Navigation("ProductCodeNavigation");
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblProductPromotion", b =>
                {
                    b.HasOne("VNVTStore.Domain.Entities.TblProduct", "ProductCodeNavigation")
                        .WithMany("TblProductPromotions")
                        .HasForeignKey("ProductCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("TblProductPromotion_ProductCode_fkey");

                    b.HasOne("VNVTStore.Domain.Entities.TblPromotion", "PromotionCodeNavigation")
                        .WithMany("TblProductPromotions")
                        .HasForeignKey("PromotionCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("TblProductPromotion_PromotionCode_fkey");

                    b.Navigation("ProductCodeNavigation");

                    b.Navigation("PromotionCodeNavigation");
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblQuote", b =>
                {
                    b.HasOne("VNVTStore.Domain.Entities.TblProduct", "ProductCodeNavigation")
                        .WithMany("TblQuotes")
                        .HasForeignKey("ProductCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("TblQuote_ProductCode_fkey");

                    b.HasOne("VNVTStore.Domain.Entities.TblUser", "UserCodeNavigation")
                        .WithMany("TblQuotes")
                        .HasForeignKey("UserCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("TblQuote_UserCode_fkey");

                    b.Navigation("ProductCodeNavigation");

                    b.Navigation("UserCodeNavigation");
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblReview", b =>
                {
                    b.HasOne("VNVTStore.Domain.Entities.TblOrderItem", "OrderItemCodeNavigation")
                        .WithMany("TblReviews")
                        .HasForeignKey("OrderItemCode")
                        .HasConstraintName("TblReview_OrderItemCode_fkey");

                    b.HasOne("VNVTStore.Domain.Entities.TblUser", "UserCodeNavigation")
                        .WithMany("TblReviews")
                        .HasForeignKey("UserCode")
                        .IsRequired()
                        .HasConstraintName("TblReview_UserCode_fkey");

                    b.Navigation("OrderItemCodeNavigation");

                    b.Navigation("UserCodeNavigation");
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblAddress", b =>
                {
                    b.Navigation("TblOrders");
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblCart", b =>
                {
                    b.Navigation("TblCartItems");
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblCategory", b =>
                {
                    b.Navigation("InverseParentCodeNavigation");

                    b.Navigation("TblProducts");
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblCoupon", b =>
                {
                    b.Navigation("TblOrders");
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblOrder", b =>
                {
                    b.Navigation("TblOrderItems");

                    b.Navigation("TblPayment");
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblOrderItem", b =>
                {
                    b.Navigation("TblReviews");
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblProduct", b =>
                {
                    b.Navigation("TblCartItems");

                    b.Navigation("TblOrderItems");

                    b.Navigation("TblProductImages");

                    b.Navigation("TblProductPromotions");

                    b.Navigation("TblQuotes");
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblPromotion", b =>
                {
                    b.Navigation("TblCoupons");

                    b.Navigation("TblProductPromotions");
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblUser", b =>
                {
                    b.Navigation("TblAddresses");

                    b.Navigation("TblCarts");

                    b.Navigation("TblOrders");

                    b.Navigation("TblQuotes");

                    b.Navigation("TblReviews");
                });
#pragma warning restore 612, 618
        }
    }
}
