// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VNVTStore.Infrastructure.Persistence;

#nullable disable

namespace VNVTStore.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260124131159_AddProductDetail")]
    partial class AddProductDetail
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("address_code_seq");

            modelBuilder.HasSequence("banner_code_seq");

            modelBuilder.HasSequence("cart_code_seq");

            modelBuilder.HasSequence("cartitem_code_seq");

            modelBuilder.HasSequence("category_code_seq");

            modelBuilder.HasSequence("coupon_code_seq");

            modelBuilder.HasSequence("file_code_seq");

            modelBuilder.HasSequence("order_code_seq");

            modelBuilder.HasSequence("orderitem_code_seq");

            modelBuilder.HasSequence("payment_code_seq");

            modelBuilder.HasSequence("product_code_seq");

            modelBuilder.HasSequence("productpromotion_code_seq");

            modelBuilder.HasSequence("promotion_code_seq");

            modelBuilder.HasSequence("quote_code_seq");

            modelBuilder.HasSequence("review_code_seq");

            modelBuilder.HasSequence("user_code_seq");

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblAddress", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValueSql("('ADR'::text || lpad((nextval('address_code_seq'::regclass))::text, 6, '0'::text))");

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Country")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValueSql("'Vietnam'::character varying");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool?>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("ModifiedType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("ADD");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Code")
                        .HasName("TblAddress_pkey");

                    b.HasIndex(new[] { "UserCode" }, "idx_address_user");

                    b.ToTable("TblAddress", (string)null);
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblBanner", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValueSql("('BNN'::text || lpad((nextval('banner_code_seq'::regclass))::text, 6, '0'::text))");

                    b.Property<string>("Content")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("LinkText")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LinkUrl")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ModifiedType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("ADD");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Code")
                        .HasName("TblBanner_pkey");

                    b.ToTable("TblBanner", (string)null);
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblBrand", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("ADD");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Code")
                        .HasName("TblBrand_pkey");

                    b.ToTable("TblBrand", (string)null);
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblCart", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValueSql("('CRT'::text || lpad((nextval('cart_code_seq'::regclass))::text, 6, '0'::text))");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("ModifiedType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("ADD");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Code")
                        .HasName("TblCart_pkey");

                    b.HasIndex(new[] { "UserCode" }, "idx_cart_user");

                    b.ToTable("TblCart", (string)null);
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblCartItem", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValueSql("('CRI'::text || lpad((nextval('cartitem_code_seq'::regclass))::text, 6, '0'::text))");

                    b.Property<DateTime?>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CartCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("ModifiedType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("ADD");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Size")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Code")
                        .HasName("TblCartItem_pkey");

                    b.HasIndex("CartCode");

                    b.HasIndex("ProductCode");

                    b.ToTable("TblCartItem", (string)null);
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblCategory", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValueSql("('CAT'::text || lpad((nextval('category_code_seq'::regclass))::text, 6, '0'::text))");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("ImageURL");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("ModifiedType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("ADD");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ParentCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Code")
                        .HasName("TblCategory_pkey");

                    b.HasIndex(new[] { "Name" }, "idx_category_name");

                    b.HasIndex(new[] { "ParentCode" }, "idx_category_parent");

                    b.ToTable("TblCategory", (string)null);
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblCoupon", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValueSql("('CPN'::text || lpad((nextval('coupon_code_seq'::regclass))::text, 6, '0'::text))");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("ModifiedType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("ADD");

                    b.Property<string>("PromotionCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("UsageCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Code")
                        .HasName("TblCoupon_pkey");

                    b.HasIndex("PromotionCode");

                    b.ToTable("TblCoupon", (string)null);
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblFile", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValueSql("('FIL'::text || lpad((nextval('file_code_seq'::regclass))::text, 6, '0'::text))");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("MasterCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MasterType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ModifiedType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("ADD");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Code")
                        .HasName("TblFile_pkey");

                    b.HasIndex(new[] { "MasterCode" }, "idx_file_mastercode");

                    b.ToTable("TblFile", (string)null);
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblOrder", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValueSql("('ORD'::text || lpad((nextval('order_code_seq'::regclass))::text, 6, '0'::text))");

                    b.Property<string>("AddressCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CouponCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal?>("DiscountAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("FinalAmount")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("ModifiedType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("ADD");

                    b.Property<DateTime?>("OrderDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("ShippingFee")
                        .HasColumnType("numeric");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValueSql("'pending'::character varying");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("VerificationToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("VerificationTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Code")
                        .HasName("TblOrder_pkey");

                    b.HasIndex("AddressCode");

                    b.HasIndex("CouponCode");

                    b.HasIndex(new[] { "OrderDate" }, "idx_order_date");

                    b.HasIndex(new[] { "Status" }, "idx_order_status");

                    b.HasIndex(new[] { "UserCode" }, "idx_order_user");

                    b.ToTable("TblOrder", (string)null);
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblOrderItem", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValueSql("('ORI'::text || lpad((nextval('orderitem_code_seq'::regclass))::text, 6, '0'::text))");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal?>("DiscountAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasDefaultValueSql("0");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("ModifiedType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("ADD");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("PriceAtOrder")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<string>("ProductCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProductImage")
                        .HasColumnType("text");

                    b.Property<string>("ProductName")
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Size")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Code")
                        .HasName("TblOrderItem_pkey");

                    b.HasIndex("OrderCode");

                    b.HasIndex("ProductCode");

                    b.ToTable("TblOrderItem", (string)null);
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblPayment", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValueSql("('PAY'::text || lpad((nextval('payment_code_seq'::regclass))::text, 6, '0'::text))");

                    b.Property<decimal>("Amount")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ModifiedType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("ADD");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("PaymentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValueSql("'pending'::character varying");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("TransactionID");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Code")
                        .HasName("TblPayment_pkey");

                    b.HasIndex(new[] { "OrderCode" }, "TblPayment_OrderCode_key")
                        .IsUnique();

                    b.ToTable("TblPayment", (string)null);
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblProduct", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValueSql("('PRD'::text || lpad((nextval('product_code_seq'::regclass))::text, 6, '0'::text))");

                    b.Property<string>("BaseUnit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("BinLocation")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BrandCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CategoryCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("CostPrice")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<string>("CountryOfOrigin")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int?>("MinStockLevel")
                        .HasColumnType("integer");

                    b.Property<string>("ModifiedType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("ADD");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<int?>("StockQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("SupplierCode")
                        .HasColumnType("character varying");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal?>("VatRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal?>("WholesalePrice")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.HasKey("Code")
                        .HasName("TblProduct_pkey");

                    b.HasIndex(new[] { "IsActive" }, "idx_product_active");

                    b.HasIndex(new[] { "BrandCode" }, "idx_product_brand");

                    b.HasIndex(new[] { "CategoryCode" }, "idx_product_category");

                    b.HasIndex(new[] { "Name" }, "idx_product_name");

                    b.HasIndex(new[] { "SupplierCode" }, "idx_product_supplier");

                    b.ToTable("TblProduct", (string)null);
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblProductDetail", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DetailType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("ADD");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SpecName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SpecValue")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Code")
                        .HasName("TblProductDetail_pkey");

                    b.HasIndex("ProductCode");

                    b.ToTable("TblProductDetail", (string)null);
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblProductPromotion", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValueSql("('PPROM'::text || lpad((nextval('productpromotion_code_seq'::regclass))::text, 6, '0'::text))");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("ModifiedType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("ADD");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PromotionCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Code")
                        .HasName("TblProductPromotion_pkey");

                    b.HasIndex("PromotionCode");

                    b.HasIndex(new[] { "ProductCode", "PromotionCode" }, "TblProductPromotion_ProductCode_PromotionCode_key")
                        .IsUnique();

                    b.ToTable("TblProductPromotion", (string)null);
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblProductTag", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("ModifiedType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("ADD");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TagCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Code")
                        .HasName("TblProductTag_pkey");

                    b.HasIndex("ProductCode");

                    b.HasIndex("TagCode");

                    b.ToTable("TblProductTag", (string)null);
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblPromotion", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValueSql("('PROM'::text || lpad((nextval('promotion_code_seq'::regclass))::text, 6, '0'::text))");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("DiscountValue")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("MaxDiscountAmount")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<decimal?>("MinOrderAmount")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<string>("ModifiedType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("ADD");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("UsageLimit")
                        .HasColumnType("integer");

                    b.HasKey("Code")
                        .HasName("TblPromotion_pkey");

                    b.ToTable("TblPromotion", (string)null);
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblQuote", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValueSql("('QT'::text || lpad((nextval('quote_code_seq'::regclass))::text, 6, '0'::text))");

                    b.Property<string>("AdminNote")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CustomerEmail")
                        .HasColumnType("text");

                    b.Property<string>("CustomerName")
                        .HasColumnType("text");

                    b.Property<string>("CustomerPhone")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("ModifiedType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("ADD");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<decimal?>("QuotedPrice")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValueSql("'pending'::character varying");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Code")
                        .HasName("TblQuote_pkey");

                    b.HasIndex("ProductCode");

                    b.HasIndex("UserCode");

                    b.ToTable("TblQuote", (string)null);
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblReview", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValueSql("('REV'::text || lpad((nextval('review_code_seq'::regclass))::text, 6, '0'::text))");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool?>("IsApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("ModifiedType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("ADD");

                    b.Property<string>("OrderItemCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Code")
                        .HasName("TblReview_pkey");

                    b.HasIndex("OrderItemCode");

                    b.HasIndex("UserCode");

                    b.ToTable("TblReview", (string)null);
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblSupplier", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("character varying");

                    b.Property<string>("Address")
                        .HasColumnType("character varying");

                    b.Property<string>("BankAccount")
                        .HasColumnType("character varying");

                    b.Property<string>("BankName")
                        .HasColumnType("character varying");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("character varying");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .HasColumnType("character varying");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("ModifiedType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("ADD");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("character varying");

                    b.Property<string>("TaxCode")
                        .HasColumnType("character varying");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Code")
                        .HasName("TblSupplier_pkey");

                    b.ToTable("TblSupplier", (string)null);
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblTag", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("ModifiedType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("ADD");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Code")
                        .HasName("TblTag_pkey");

                    b.ToTable("TblTag", (string)null);
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblUnit", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("ConversionRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("ADD");

                    b.Property<decimal>("Price")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Code")
                        .HasName("TblUnit_pkey");

                    b.HasIndex("ProductCode");

                    b.ToTable("TblUnit", (string)null);
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblUser", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValueSql("('USR'::text || lpad((nextval('user_code_seq'::regclass))::text, 6, '0'::text))");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EmailVerificationToken")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LoyaltyPoints")
                        .HasColumnType("integer")
                        .HasColumnName("LoyaltyPoints");

                    b.Property<string>("ModifiedType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Add");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ResetTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValueSql("'customer'::character varying");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Code")
                        .HasName("TblUser_pkey");

                    b.HasIndex(new[] { "Email" }, "TblUser_Email_key")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "TblUser_Username_key")
                        .IsUnique();

                    b.HasIndex(new[] { "Phone" }, "idx_user_phone");

                    b.ToTable("TblUser", (string)null);
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblAddress", b =>
                {
                    b.HasOne("VNVTStore.Domain.Entities.TblUser", "UserCodeNavigation")
                        .WithMany("TblAddresses")
                        .HasForeignKey("UserCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("TblAddress_UserCode_fkey");

                    b.Navigation("UserCodeNavigation");
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblCart", b =>
                {
                    b.HasOne("VNVTStore.Domain.Entities.TblUser", "UserCodeNavigation")
                        .WithMany("TblCarts")
                        .HasForeignKey("UserCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("TblCart_UserCode_fkey");

                    b.Navigation("UserCodeNavigation");
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblCartItem", b =>
                {
                    b.HasOne("VNVTStore.Domain.Entities.TblCart", "CartCodeNavigation")
                        .WithMany("TblCartItems")
                        .HasForeignKey("CartCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("TblCartItem_CartCode_fkey");

                    b.HasOne("VNVTStore.Domain.Entities.TblProduct", "ProductCodeNavigation")
                        .WithMany("TblCartItems")
                        .HasForeignKey("ProductCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("TblCartItem_ProductCode_fkey");

                    b.Navigation("CartCodeNavigation");

                    b.Navigation("ProductCodeNavigation");
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblCategory", b =>
                {
                    b.HasOne("VNVTStore.Domain.Entities.TblCategory", "ParentCodeNavigation")
                        .WithMany("InverseParentCodeNavigation")
                        .HasForeignKey("ParentCode")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("TblCategory_ParentCode_fkey");

                    b.Navigation("ParentCodeNavigation");
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblCoupon", b =>
                {
                    b.HasOne("VNVTStore.Domain.Entities.TblPromotion", "PromotionCodeNavigation")
                        .WithMany("TblCoupons")
                        .HasForeignKey("PromotionCode")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("TblCoupon_PromotionCode_fkey");

                    b.Navigation("PromotionCodeNavigation");
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblOrder", b =>
                {
                    b.HasOne("VNVTStore.Domain.Entities.TblAddress", "AddressCodeNavigation")
                        .WithMany("TblOrders")
                        .HasForeignKey("AddressCode")
                        .HasConstraintName("TblOrder_AddressCode_fkey");

                    b.HasOne("VNVTStore.Domain.Entities.TblCoupon", "CouponCodeNavigation")
                        .WithMany("TblOrders")
                        .HasForeignKey("CouponCode")
                        .HasConstraintName("TblOrder_CouponCode_fkey");

                    b.HasOne("VNVTStore.Domain.Entities.TblUser", "UserCodeNavigation")
                        .WithMany("TblOrders")
                        .HasForeignKey("UserCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("TblOrder_UserCode_fkey");

                    b.Navigation("AddressCodeNavigation");

                    b.Navigation("CouponCodeNavigation");

                    b.Navigation("UserCodeNavigation");
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblOrderItem", b =>
                {
                    b.HasOne("VNVTStore.Domain.Entities.TblOrder", "OrderCodeNavigation")
                        .WithMany("TblOrderItems")
                        .HasForeignKey("OrderCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("TblOrderItem_OrderCode_fkey");

                    b.HasOne("VNVTStore.Domain.Entities.TblProduct", "ProductCodeNavigation")
                        .WithMany("TblOrderItems")
                        .HasForeignKey("ProductCode")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("TblOrderItem_ProductCode_fkey");

                    b.Navigation("OrderCodeNavigation");

                    b.Navigation("ProductCodeNavigation");
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblPayment", b =>
                {
                    b.HasOne("VNVTStore.Domain.Entities.TblOrder", "OrderCodeNavigation")
                        .WithOne("TblPayment")
                        .HasForeignKey("VNVTStore.Domain.Entities.TblPayment", "OrderCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("TblPayment_OrderCode_fkey");

                    b.Navigation("OrderCodeNavigation");
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblProduct", b =>
                {
                    b.HasOne("VNVTStore.Domain.Entities.TblBrand", "Brand")
                        .WithMany("TblProducts")
                        .HasForeignKey("BrandCode")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VNVTStore.Domain.Entities.TblCategory", "CategoryCodeNavigation")
                        .WithMany("TblProducts")
                        .HasForeignKey("CategoryCode")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("TblProduct_CategoryCode_fkey");

                    b.HasOne("VNVTStore.Domain.Entities.TblSupplier", "SupplierCodeNavigation")
                        .WithMany()
                        .HasForeignKey("SupplierCode")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Brand");

                    b.Navigation("CategoryCodeNavigation");

                    b.Navigation("SupplierCodeNavigation");
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblProductDetail", b =>
                {
                    b.HasOne("VNVTStore.Domain.Entities.TblProduct", "Product")
                        .WithMany("TblProductDetails")
                        .HasForeignKey("ProductCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("TblProductDetail_ProductCode_fkey");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblProductPromotion", b =>
                {
                    b.HasOne("VNVTStore.Domain.Entities.TblProduct", "ProductCodeNavigation")
                        .WithMany("TblProductPromotions")
                        .HasForeignKey("ProductCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("TblProductPromotion_ProductCode_fkey");

                    b.HasOne("VNVTStore.Domain.Entities.TblPromotion", "PromotionCodeNavigation")
                        .WithMany("TblProductPromotions")
                        .HasForeignKey("PromotionCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("TblProductPromotion_PromotionCode_fkey");

                    b.Navigation("ProductCodeNavigation");

                    b.Navigation("PromotionCodeNavigation");
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblProductTag", b =>
                {
                    b.HasOne("VNVTStore.Domain.Entities.TblProduct", "Product")
                        .WithMany("TblProductTags")
                        .HasForeignKey("ProductCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("TblProductTag_ProductCode_fkey");

                    b.HasOne("VNVTStore.Domain.Entities.TblTag", "Tag")
                        .WithMany("TblProductTags")
                        .HasForeignKey("TagCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("TblProductTag_TagCode_fkey");

                    b.Navigation("Product");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblQuote", b =>
                {
                    b.HasOne("VNVTStore.Domain.Entities.TblProduct", "ProductCodeNavigation")
                        .WithMany("TblQuotes")
                        .HasForeignKey("ProductCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("TblQuote_ProductCode_fkey");

                    b.HasOne("VNVTStore.Domain.Entities.TblUser", "UserCodeNavigation")
                        .WithMany("TblQuotes")
                        .HasForeignKey("UserCode")
                        .HasConstraintName("TblQuote_UserCode_fkey");

                    b.Navigation("ProductCodeNavigation");

                    b.Navigation("UserCodeNavigation");
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblReview", b =>
                {
                    b.HasOne("VNVTStore.Domain.Entities.TblOrderItem", "OrderItemCodeNavigation")
                        .WithMany("TblReviews")
                        .HasForeignKey("OrderItemCode")
                        .HasConstraintName("TblReview_OrderItemCode_fkey");

                    b.HasOne("VNVTStore.Domain.Entities.TblUser", "UserCodeNavigation")
                        .WithMany("TblReviews")
                        .HasForeignKey("UserCode")
                        .IsRequired()
                        .HasConstraintName("TblReview_UserCode_fkey");

                    b.Navigation("OrderItemCodeNavigation");

                    b.Navigation("UserCodeNavigation");
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblUnit", b =>
                {
                    b.HasOne("VNVTStore.Domain.Entities.TblProduct", "Product")
                        .WithMany("TblUnits")
                        .HasForeignKey("ProductCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("TblUnit_ProductCode_fkey");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblAddress", b =>
                {
                    b.Navigation("TblOrders");
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblBrand", b =>
                {
                    b.Navigation("TblProducts");
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblCart", b =>
                {
                    b.Navigation("TblCartItems");
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblCategory", b =>
                {
                    b.Navigation("InverseParentCodeNavigation");

                    b.Navigation("TblProducts");
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblCoupon", b =>
                {
                    b.Navigation("TblOrders");
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblOrder", b =>
                {
                    b.Navigation("TblOrderItems");

                    b.Navigation("TblPayment");
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblOrderItem", b =>
                {
                    b.Navigation("TblReviews");
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblProduct", b =>
                {
                    b.Navigation("TblCartItems");

                    b.Navigation("TblOrderItems");

                    b.Navigation("TblProductDetails");

                    b.Navigation("TblProductPromotions");

                    b.Navigation("TblProductTags");

                    b.Navigation("TblQuotes");

                    b.Navigation("TblUnits");
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblPromotion", b =>
                {
                    b.Navigation("TblCoupons");

                    b.Navigation("TblProductPromotions");
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblTag", b =>
                {
                    b.Navigation("TblProductTags");
                });

            modelBuilder.Entity("VNVTStore.Domain.Entities.TblUser", b =>
                {
                    b.Navigation("TblAddresses");

                    b.Navigation("TblCarts");

                    b.Navigation("TblOrders");

                    b.Navigation("TblQuotes");

                    b.Navigation("TblReviews");
                });
#pragma warning restore 612, 618
        }
    }
}
